////////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gen model, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST              //
////////////////////////////////////////////////////////////

package project

import "time"

//go:generate gormgen -s Project -i .
type Project struct {
	Id         int32     `json:"id"`                     //
	Title      string    `json:"title"`                  //
	Desc       string    `json:"desc"`                   //
	GitUrl     string    `json:"git_url"`                //
	GitType    int32     `json:"git_type"`               //
	GitBranch  string    `json:"git_branch"`             //
	ClusterIds string    `json:"cluster_ids"`            //
	CreatedAt  time.Time `json:"created_at" gorm:"time"` //
	UpdatedAt  time.Time `json:"updated_at" gorm:"time"` //
}

func (_ *Project) TableName() string {
	return "projects"
}
